-- Table: account

DROP TABLE IF EXISTS `account`;
CREATE TABLE `account` (
  `account_id` int NOT NULL AUTO_INCREMENT,
  `account_code` varchar(25) NOT NULL,
  `email` varchar(150) NOT NULL,
  `primary_phone` varchar(10) NOT NULL,
  `primary_phone_country` varchar(5) NOT NULL,
  `primary_phone_type` int NOT NULL DEFAULT '1',
  `secondary_phone` varchar(10) DEFAULT NULL,
  `secondary_phone_country` varchar(5) DEFAULT NULL,
  `secondary_phone_type` int DEFAULT NULL,
  `first_name` varchar(45) NOT NULL,
  `last_name` varchar(45) NOT NULL,
  `middle_name` varchar(45) DEFAULT NULL,
  `birth_date` date NOT NULL,
  `gender` int NOT NULL,
  `address_line1` varchar(45) NOT NULL,
  `address_line2` varchar(45) DEFAULT NULL,
  `city` varchar(45) NOT NULL,
  `state` varchar(45) NOT NULL,
  `zip` varchar(45) NOT NULL,
  `country` varchar(45) NOT NULL,
  `photo` varchar(45) DEFAULT NULL,
  `secret_question` varchar(45) DEFAULT NULL,
  `secret_answer` varchar(45) DEFAULT NULL,
  `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_user` varchar(45) DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  `modified_user` varchar(45) DEFAULT NULL,
  `is_active` tinyint DEFAULT NULL,
  `activation_date` datetime DEFAULT NULL,
  `activated_user` varchar(45) DEFAULT NULL,
  `deactivated_date` datetime DEFAULT NULL,
  `deactivated_user` varchar(45) DEFAULT NULL,
  `deactivation_reason` varchar(500) DEFAULT NULL,
  `is_deleted` tinyint DEFAULT NULL,
  `deleted_date` datetime DEFAULT NULL,
  `deleted_user` varchar(45) DEFAULT NULL,
  `deleted_reason` varchar(500) DEFAULT NULL,
  `driving_license` varchar(45) DEFAULT NULL,
  `registered_partner_id` int DEFAULT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE KEY `IDX_cb612e381caefdc3968e7d55e3` (`account_code`)
) ENGINE=InnoDB;
