-- Table: profile_personal

DROP TABLE IF EXISTS `profile_personal`;
CREATE TABLE `profile_personal` (
  `profile_id` int NOT NULL AUTO_INCREMENT,
  `account_id` int NOT NULL,
  `first_name` varchar(50) NOT NULL,
  `last_name` varchar(50) NOT NULL,
  `middle_name` varchar(50) DEFAULT NULL,
  `prefix` varchar(10) DEFAULT NULL,
  `suffix` varchar(10) DEFAULT NULL,
  `gender` int NOT NULL COMMENT '1=Male, 2=Female, 3=Other',
  `birth_date` date NOT NULL,
  `phone_mobile` varchar(20) NOT NULL,
  `phone_home` varchar(20) DEFAULT NULL,
  `phone_emergency` varchar(20) DEFAULT NULL,
  `email_id` varchar(100) NOT NULL,
  `marital_status` int NOT NULL,
  `religion` int DEFAULT NULL,
  `nationality` int DEFAULT NULL,
  `caste` int DEFAULT NULL,
  `height_inches` decimal(5,2) DEFAULT NULL,
  `height_cms` decimal(5,2) DEFAULT NULL,
  `weight` decimal(5,2) DEFAULT NULL,
  `weight_units` varchar(10) DEFAULT NULL COMMENT 'kg, lbs',
  `complexion` int DEFAULT NULL,
  `linkedin` varchar(255) DEFAULT NULL,
  `facebook` varchar(255) DEFAULT NULL,
  `instagram` varchar(255) DEFAULT NULL,
  `whatsapp_number` varchar(20) DEFAULT NULL,
  `profession` int DEFAULT NULL,
  `disability` int DEFAULT NULL,
  `created_user` varchar(100) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_user` varchar(100) DEFAULT NULL,
  `updated_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` tinyint DEFAULT '1',
  `short_summary` longtext,
  `birth_time` time DEFAULT NULL,
  `birth_pace` varchar(55) DEFAULT NULL,
  `blood_group` int DEFAULT NULL,
  PRIMARY KEY (`profile_id`),
  KEY `idx_profile_personal_email` (`email_id`),
  KEY `idx_profile_personal_active` (`is_active`)
) ENGINE=InnoDB;
