-- Table: registered_partner

DROP TABLE IF EXISTS `registered_partner`;
CREATE TABLE `registered_partner` (
  `reg_partner_id` int NOT NULL AUTO_INCREMENT,
  `business_name` varchar(155) NOT NULL,
  `alias` varchar(45) NOT NULL,
  `business_email` varchar(155) DEFAULT NULL,
  `primary_phone` varchar(10) NOT NULL,
  `primary_phone_country_code` int NOT NULL,
  `secondary_phone` varchar(10) DEFAULT NULL,
  `address_line1` varchar(150) NOT NULL,
  `city` varchar(45) DEFAULT NULL,
  `state` int NOT NULL,
  `country` int NOT NULL,
  `zip` varchar(8) NOT NULL,
  `business_registration_number` varchar(155) NOT NULL,
  `business_ITIN` varchar(155) NOT NULL,
  `business_description` varchar(255) NOT NULL,
  `primary_contact_first_name` varchar(45) NOT NULL,
  `primary_contact_last_name` varchar(45) NOT NULL,
  `primary_contact_gender` int DEFAULT NULL,
  `primary_contact_date_of_birth` date DEFAULT NULL,
  `primary_contact_email` varchar(45) DEFAULT NULL,
  `business_linkedin` varchar(155) DEFAULT NULL,
  `business_website` varchar(155) NOT NULL,
  `business_facebook` varchar(155) DEFAULT NULL,
  `business_whatsapp` varchar(155) DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  `user_created` varchar(45) DEFAULT NULL,
  `date_modified` datetime DEFAULT NULL,
  `user_modified` varchar(45) DEFAULT NULL,
  `isverified` int DEFAULT '0',
  `Is_active` bit(1) DEFAULT b'0',
  `activation_date` timestamp NULL DEFAULT NULL,
  `domain_root_url` varchar(255) DEFAULT NULL,
  `verification_comment` varchar(255) DEFAULT NULL,
  `verification_status` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`reg_partner_id`)
) ENGINE=InnoDB;
