-- Table: profile_family_reference

DROP TABLE IF EXISTS `profile_family_reference`;
CREATE TABLE `profile_family_reference` (
  `profile_family_reference_id` int NOT NULL AUTO_INCREMENT,
  `profile_id` int NOT NULL,
  `reference_type` int DEFAULT NULL,
  `first_name` varchar(45) NOT NULL,
  `last_name` varchar(45) NOT NULL,
  `middle_name` varchar(45) DEFAULT NULL,
  `alias` varchar(45) DEFAULT NULL,
  `gender` int DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `religion` int DEFAULT NULL,
  `nationality` int DEFAULT NULL,
  `caste` int DEFAULT NULL,
  `marital_status` int DEFAULT NULL,
  `highest_education` int DEFAULT NULL,
  `disability` int DEFAULT NULL,
  `address_line1` varchar(50) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `state` int NOT NULL,
  `country` int NOT NULL,
  `zip` varchar(8) NOT NULL,
  `primary_phone` varchar(45) NOT NULL,
  `secondary_phone` varchar(45) DEFAULT NULL,
  `can_communicate` tinyint NOT NULL,
  `email` varchar(45) DEFAULT NULL,
  `linkedin` varchar(45) DEFAULT NULL,
  `instagram` varchar(45) DEFAULT NULL,
  `facebook` varchar(45) DEFAULT NULL,
  `whatsapp` varchar(45) DEFAULT NULL,
  `employment_status` int DEFAULT NULL,
  `emp_company_name` varchar(45) DEFAULT NULL,
  `emp_city` varchar(45) DEFAULT NULL,
  `emp_state` varchar(45) DEFAULT NULL,
  `emp_country` varchar(45) DEFAULT NULL,
  `emp_zip` varchar(8) DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  `user_created` varchar(45) DEFAULT NULL,
  `date_modified` datetime DEFAULT NULL,
  `user_modified` varchar(45) DEFAULT NULL,
  `isverified` int DEFAULT '0',
  PRIMARY KEY (`profile_family_reference_id`)
) ENGINE=InnoDB;
